version: '3'

services:
  app:
    build:
      context: .
      target: production
    hostname: mydocker
    environment:
      PORT: 1337
      REDIS_HOST: redis
      REDIS_PORT: 6379
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PORT: 3306
      MYSQL_DB: ${MYSQL_DB}
      MYSQL_USERNAME: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      FILE_PATH_TO_CHECK: ${FILE_PATH_TO_CHECK}
    ports:
      - "1337:1337"
    volumes:
      - .:/app
    depends_on:
      - mysql
      - redis

  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_USER: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./my.cnf:/etc/mysql/my.cnf

  redis:
    image: redis:latest
    restart: always

volumes:
  mysql-data:
